version: '3.8'

services:
  backend:
    build: .
    container_name: psychology-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/psychology_db
      SPRING_DATASOURCE_USERNAME: psychology_user
      SPRING_DATASOURCE_PASSWORD: psychology_pass
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_SEED_ENABLED: "true"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      args:
        VITE_TURN_URL: ${VITE_TURN_URL}
        VITE_TURN_USER: ${VITE_TURN_USER}
        VITE_TURN_PASS: ${VITE_TURN_PASS}
    container_name: psychology-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  postgres:
    image: postgres:15-alpine
    container_name: psychology-postgres
    environment:
      POSTGRES_DB: psychology_db
      POSTGRES_USER: psychology_user
      POSTGRES_PASSWORD: psychology_pass
      POSTGRES_ADMIN_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U psychology_user -d psychology_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: psychology-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

#  coturn:
#    image: instrumentisto/coturn:4.6.2
#    container_name: psychology-coturn
#    restart: unless-stopped
#    ports:
#      - "3478:3478/tcp"
#      - "3478:3478/udp"
#      - "49160-49200:49160-49200/udp"
#    environment:
#      TURN_USER: ${TURN_USER:-turnuser}
#      TURN_PASS: ${TURN_PASS:-turnpass}
#      TURN_REALM: ${TURN_REALM:-188.225.45.82}
#      TURN_EXTERNAL_IP: ${TURN_EXTERNAL_IP:-188.225.45.82}
#    command:
#      - -n
#      - --log-file=stdout
#      - --lt-cred-mech
#      - --user=$(TURN_USER):$(TURN_PASS)
#      - --realm=$(TURN_REALM)
#      - --external-ip=$(TURN_EXTERNAL_IP)
#      - --min-port=49160
#      - --max-port=49200
#      - --no-tls
#      - --no-dtls

volumes:
  postgres_data:
  redis_data:
